### PR TITLE
Overriding operator new for Heavy_{{name}} class, so that heap allocation returns aligned memory. 

### PR DESCRIPTION
**Pull request by giuliomoro**
Closes https://github.com/enzienaudio/hvcc/issues/18

This one had been left out of the previous PR (this is actually an improved  version of that commit). Everything else seems to be OK, as far as I could test. Thanks

### CODE REVIEW

**Comment by dromer** [comment]
We cannot throw exceptions in the way you are doing and this is breaking compilation in the tests.

Please check if this can be done differently. Also realize that this likely won't work for other (embedded) targets either.

**Comment by dromer** [comment]
We cannot throw exceptions in the way you are doing and this is breaking compilation in the tests.

Please check if this can be done differently. Also realize that this likely won't work for other (embedded) targets either.

**Comment by giuliomoro** [comment]
new commit makes tests pass, is that good enough?

**Comment by dromer** [comment]
Well it passes the tests at least, but do you have a test-case/patch where this occurs?
We need to be sure that this doesn't break other targets.

**Comment by giuliomoro** [comment]
IIRC the deal is that heap allocation of types with strict memory alignment requirements is not enforced to be properly aligned before c++17. The `Heavy_{{name}}` class may have 128-bit boundary memory alignment requirements if it includes arm neon intrinsics as it often does (and I must guess this is true also for x86 intrinsics elsewhere). This means that when using intrinsics _and_ using a standard version < c++17 _and_ you allocate on the heap, you _may_ get wrong alignment. I have had instances where `clang` on ARM would produce such a result. This case is caught by the check in the constructor, while the override for `operator new` ensures this works well when heap allocation happens via `operator new`. Sure there are other ways of allocating on the heap, but I only covered the most common one, hence the check in the constructor.

As for what happens on other platforms, I haven't tested any, but:
- when intrinsics are not enabled, the constructor check shouldn't fail because the alignment requirements are less strict
- I am not _overaligning_, I am explicitly checking `alignof(Heavy_{{name}})`, so if it fails it is doing a favour of failing at construction and not failing with a BUS ERROR when trying to use a SIMD on unaligned memory- on platforms without exceptions, the only changes is to allocate aligned with `operator new` in which case I am doing nothing more than enforcing the requested alignment.
- `aligned_alloc(alignof(Heavy_{{name}}), sz)` fails in `operator new` only if you are out of memory (and the default `operator new` would throw (with excpetions) or return a `nullptr` (without exceptions) exactly the same way)

Again, IIRC all of this is unneeded in c++17, so we could `#ifdef` all the changes out if we have more modern C++ in use by the compiler.

**Comment by dromer** [comment]
Can you check on the changes I posted on https://github.com/Wasted-Audio/hvcc/pull/56/files ?

This was suggested by @falktx as a better way to align memory (crossplat) and frees the context correctly in the destructor.

**Comment by falkTX** [comment]
To be clear: the proposed solution here on this PR is also cross-platform, but overriding new operator seems very ugly.

**Comment by dromer** [comment]
@giuliomoro can you please check out https://github.com/Wasted-Audio/hvcc/pull/56 ?
If this solves your issue then I prefer using that solution. This also pushes for explicit freeing of the context, which I think should be preferable.

**Comment by giuliomoro** [comment]
Sorry for jumping back on this so late. It seems to me that #56 doesn't quite fix the issue if one calls `new Heavy_{{name}}()` directly. There are two instances where this happens in the templates code:

https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/c2wwise/templates/source/engine/Hv_%7B%7Bname%7D%7D_Wwise%7B%7Btype%7D%7DPluginEngine.cpp#L96
https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/c2unity/templates/source/unity/Hv_%7B%7Bname%7D%7D_AudioPlugin.cpp#L46

and there may be some user code out there which can do the same. I cannot comment on the ugliness of overriding `operator new`, but I can tell how painful this bug was to track down for me. So I would recommend at least reinstating the runtime check from the within the constructor. E.g.:

```
diff --git a/hvcc/generators/ir2c/templates/Heavy_NAME.cpp b/hvcc/generators/ir2c/templates/Heavy_NAME.cpp
index ff61072..1181cbe 100644
--- a/hvcc/generators/ir2c/templates/Heavy_NAME.cpp
+++ b/hvcc/generators/ir2c/templates/Heavy_NAME.cpp
@@ -32,7 +32,14 @@ extern "C" {
 {%- endfor %}
 {%- endif %}

-
+#ifdef __EXCEPTIONS
+class my_bad_alloc : public std::bad_alloc {
+  virtual const char* what() const noexcept
+  {
+    return "Heavy_{{name}} object is improperly aligned. Avoid heap allocation or use -std=c++17\n";
+  }
+};
+#endif // __EXCEPTIONS

 /*
  * Class Functions
@@ -40,6 +47,13 @@ extern "C" {

 Heavy_{{name}}::Heavy_{{name}}(double sampleRate, int poolKb, int inQueueKb, int outQueueKb)
     : HeavyContext(sampleRate, poolKb, inQueueKb, outQueueKb) {
+#ifdef __EXCEPTIONS
+  if(size_t(this) & size_t(alignof(Heavy_{{name}}) - 1))
+  {
+    my_bad_alloc e;
+    throw(e);
+  }
+#endif // __EXCEPTIONS
   {%- for x in init_list %}
   numBytes += {{x}}
   {%- endfor %}
```

**Comment by dromer** [comment]
I think the fix would be to simply not call this constructor and use the `hv_{{name}}_new_with_options()` constructor instead, no?

We can simply modify these templates if needed. If users have faulty code then users need to update their code, imo.

**Comment by giuliomoro** [comment]
> If users have faulty code then users need to update their code, imo.

Kind of fair, but how would they know they have faulty code in the first place? That's why I am suggesting reinstating the runtime check at least.

As for the "kind of" part, what is the point of having a C++ API if one cannot reliably use `new` to create an object instance, or put it in a `std::vector`, or as a member of a different class? The runtime check detects any alignment errors in all these cases. Again, I appreciate this is only for pre-C++17, so not particularly relevant these days, but adding the runtime check costs very little.

**Comment by dromer** [comment]
Well currently almost nobody uses this fork, so any code you are referring to would not be using any of these fixes anyway :)

**Comment by giuliomoro** [comment]
what? what forks are they using then?

**Comment by dromer** [comment]
People are either still using the original enzienaudio, their own forks or any that you can see here: https://github.com/enzienaudio/hvcc/network

So far I don't think there are that many users of my fork yet, but I might be mistaken :)

(I know only Electro Smith Daisy actively uses it)

**Comment by giuliomoro** [comment]
but this fork has python3 support ! What's not to like?

**Comment by dromer** [comment]
Haha, I agree!

**Comment by falkTX** [comment]
an alternative approach here is to make the constructor private, so `new Heavy[...]()` does not build anymore.
that way you are forced to use the C style allocators.

**Pull request closed without merging**
