### PR TITLE
fix: if os is Windows call emcc via batch not shell script

### PR DESCRIPTION
**Pull request by vulcu**
On Windows (possibly only on some systems), calling `which("emcc")` in Python returns the path to the emcc shell script entry point used by Unix systems, and not the batch file entry point required to run emcc from Window's `cmd` shell.

This PR adds a quick check to ensure the correct script is pointed to when running HVCC on Windows systems. The emcc shell script has no `.sh` extension, so appending `.bat` is sufficient to fix the issue.

### CODE REVIEW

**Comment by vulcu** [comment]
just realized I should have put this after the `if emcc_path is None` conditional, not before it

**Comment by dromer** [comment]
This is not correct. `which()` searches for the `emcc` command, not the `emcc.sh` command.

Please check if on your os if `which("emcc.bat")` works. Then the check needs to happen _before_ `which()` is called.

**Comment by dromer** [comment]
@vulcu this works correctly for on windows now?

**Comment by vulcu** [comment]
@dromer Yes, I have tested it on two different windows machines I have. It works as expected on both systems. One caveat is that I have only tested using MinGW and/or MSYS2, and not when running python in cmd or powershell. Let me know and I can test those too, although would not expect a different result.

**Comment by dromer** [comment]
Would be a nice test yeah. If you can test that as well than I'll merge it right away!

**Comment by vulcu** [comment]
Okay, I've tested it on two windows machines when running python from cmd and from powershell, and it works as expected. I think we're good!

**Pull request merged**
