### PR TITLE
Implement tabplay~

### LINKED ISSUE #100: tabplay~ implementation broken
It's giving recursion errors, which is because the current heavy abstraction contains another tabplay~ ...

This abstraction seems to not be complete, which means it will need some work to properly implement and verify.

### PR DESCRIPTION
**Pull request by dromer**
Hopefully can close #100 

Basically copied what `tabread~.pd` does, except for control-only inlet and using `__hv_tabread_stoppable_f`.

What is at least missing:
- [x] respond to `[stop(` message
- [x] start and length message with `[500 2000(`
- [x] output a bang on the right outlet when it reaches the end of the table - ~~I currently don't see a way to trigger a bang from a signal object function: leave out as "known limitation" ?~~

### CODE REVIEW

**Review by filipeborato — APPROVED** [review]

**Comment by dromer** [comment]
@filipeborato did you test this? I don't think it works yet ..

**Comment by filipeborato** [comment]
@dromer I haven't tested it yet, but I can test it to see what's going on.

**Comment by dromer** [comment]
@filipeborato then why approve? :P

**Comment by filipeborato** [comment]
@dromer because I thought you were beautiful...

**Comment by filipeborato** [comment]
@dromer I think these initiatives are really cool, I approve of that.  I'm looking for a project to participate...

**Comment by dromer** [comment]
I think this is done! Can someone test and confirm this please? :)

Would also be good to make sure that other tabread~ like objects are still functional as well, an I've modified `sTabread_onMessage()` quite a bit.

**Comment by dromer** [comment]
My current test patch. It's just the tabplay~ help file, with the sample saved into the canvas.

**Review by filipeborato — APPROVED** [review]

**Comment by dromer** [comment]
@filipeborato did you test it this time? No comments?

I hope you understand how code review works.

**Pull request merged**
