### PR TITLE
Fix customisable message lists

### PR DESCRIPTION
**Pull request by giuliomoro**
I was sending a message with 32 elements and it was failing. Now you can send up to 63 elements. If someone needs more (or less) they can do so using `#define HV_MP_NUM_MESSAGE_LISTS X`. Where (32 << X) is the max message size. Message size is 8 + 8 * numElements.

### CODE REVIEW

**Comment by dromer** [comment]
@giuliomoro can you give an example patch where this PR is relevant (and so it can be tested)?

**Comment by giuliomoro** [comment]
hmmm try this C++ code:

```
#include <stdio.h>
#include <Heavy_example.h>

void printHook(HeavyContextInterface *context, const char *printLabel, const char *msgString, const HvMessage *msg) {
	const double timestampSecs = ((double) hv_msg_getTimestamp(msg)) / hv_getSampleRate(context);
 	printf("print: [@ %.3f] %s: %s\n", timestampSecs, printLabel, msgString);
}

int main() {
	HeavyContextInterface *gHeavyContext = hv_example_new_with_options(44100, 2, 2, 0);
	hv_setPrintHook(gHeavyContext, printHook);

	unsigned int numElements = 40;
	HvMessage* m = (HvMessage *)hv_alloca(hv_msg_getByteSize(numElements));
	hv_msg_init(m, numElements, 0);
	for(unsigned int n = 0; n < numElements; ++n)
		hv_msg_setFloat(m, n, n + 0.1f /*or whatev*/);
	hv_sendMessageToReceiver(gHeavyContext, hv_stringToHash("myrecv"), 0, m);
	int frames = 16;
	hv_processInline(gHeavyContext, 0, 0, frames);
	return 0;
}
```
and this Pd Patch:
```
[r myrecv]
|
[print mystuff]
```

without this commit, the above would fail at runtime with
```
Assertion failed: (i < 4), function mp_addMessage, file c/HvMessagePool.c, line 121.
Abort trap: 6
```
when `numElements >= 16` on `macos x86` or when  `numElements >= 32` on `Linux armv7`. I think this is platform dependent (possibly depending on pointer size).

**Comment by dromer** [comment]
Sorry I don't understand the context, when would you have these many elements in a message?

**Comment by giuliomoro** [comment]
this is for sending messages from C++ wrapper into the Pd patch. In my case I needed to send messages with 31 elements when reading from Trill Craft, which has 30 sensor pads + one symbol for routing. Here it is: https://github.com/BelaPlatform/Bela/blob/dev/scripts/hvresources/render.cpp#L736-L742

**Comment by dromer** [comment]
I see, thnx. I wonder how we can actually test this in the CI.

Also wondering if this could give problems on 32bit systems, do you know?

**Comment by giuliomoro** [comment]
>Also wondering if this could give problems on 32bit systems, do you know?

This fix was tested to work on Bela, which is 32bit armv7l.

> . I wonder how we can actually test this in the CI.

I don't know what that is currently doing, or how, and a quick browse of the repo didn't  enlighten me. I guess it would be useful to understand it so I can also help testing midi stuff. Where do you suggest I start from?

**Comment by dromer** [comment]
> This fix was tested to work on Bela, which is 32bit armv7l.
Right, I forgot the BBB is 32bit :D
(I was mainly worried about the STM32 platforms like OWL and Daisy, but I suppose this may not be a problem)

> I don't know what that is currently doing, or how, and a quick browse of the repo didn't enlighten me. I guess it would be useful to understand it so I can also help testing midi stuff. Where do you suggest I start from?

See for instance how I implemented `[stripnote]` and test: https://github.com/Wasted-Audio/hvcc/commit/781e8b8350e7448347b732a234130505353c0d58

Here I simply added a test-patch that will print to console, which is then compared to a "golden" file that includes how plain Pd would print to console.

**Comment by dromer** [comment]
Can I suggest that we leave it at 4, but allow the override for your specific implementation?

(also not sure if we can't find a cleaner way to "fix" the gh-action. maybe just remove the single quotes around the first echo?)

**Comment by giuliomoro** [comment]
thanks for taking action, sorry for the unresponsiveness.

**Pull request closed without merging**
