### PR TITLE
c2js improvements

### PR DESCRIPTION
**Pull request by dromer**
some focus on js and webasm on current `emcc`

### CODE REVIEW

**Comment by chrisuehlinger** [comment]
Hey! I've been banging my head against a wall the past couple days trying to get hvcc to compile to JS* and it was this branch that finally allowed me to get things working. I'd recommend the maintainers take a look at this, it'll likely help a lot of people in the future!

*It's pretty hard to get ahold of a working copy of Emscripten v1.37.38 in 2022. You have to compile from source, and some of the dependencies have trouble compiling but don't emit error messages. With this branch I was able to use v1.38.33, which is the oldest version that is available precompiled.

**Comment by dromer** [comment]
You should be able to use the latest emcc with this branch.

One issue is that the html/js wrapper is severely outdated and doesn't work properly any more, so this branch still needs work before it can be merged.

If you have success integrating the resulting webasm in a webpage don't hesitate to contribute ;)

**Comment by chrisuehlinger** [comment]
> If you have success integrating the resulting webasm in a webpage

I have! So are you just looking to add a button to get around the modern AutoplayPolicy nonsense? Or are you also looking to upgrade to AudioWorklets?

**Comment by chrisuehlinger** [comment]
Not sure how y'all want to handle this (e.g. add it to this PR, merge my branch into this branch) but here's what I've got on the "get it running with the latest emscripten" front. https://github.com/chrisuehlinger/hvcc/commit/f829d626168822686b3d7283f5c13d104fb61b87

**Comment by chrisuehlinger** [comment]
Regarding AudioWorklets (if that's something you want) what kind of browser support are you aiming for? I've noticed that you're still compiling to asm.js even though [93% of users](https://caniuse.com/wasm) have browsers that support WASM. AudioWorklets have [similar support](https://caniuse.com/mdn-api_audioworklet), although as you add up the permutations (asm.js+AudioWorklet, WASM+ScriptProcessorNode, etc) it could start to get hairy.

With that being said, the reason I bring this up is that ScriptProcessorNode has been deprecated for a while, and it feels like only a matter of time before some new feature that users might want is incompatible with it.

**Comment by dromer** [comment]
Yes, the current wrapper implementation uses deprecated methods and it would be nice to modernize it.
My knowledge of JS and AudioWorklets are extremely limited and I haven't been able to see a path to migrate it.

Any help with this is appreciated (indeed a PR to this branch would be best).

**Comment by chrisuehlinger** [comment]
I'll get a PR going this evening EDT. I've worked with the Web Audio API for years and have been meaning to learn more about AudioWorklets, so I'd be happy to take a crack at that too. Do you have a Pd patch in the test folder that's good for "stress testing"?

**Comment by dromer** [comment]
Haha, not really. I'm planning to make a couple of example patches this weekend, so we can use those perhaps (would be relatively generic, but currently focusing on dpf, owl and daisy).

**Comment by dromer** [comment]
@chrisuehlinger what where the main TODO items you where thinking of?

Since we do have functional wasm export with this I'm tempted to just merge it into develop. Any further improvements and/or bugfixes can always come in later.

For now it would already be a huge step forward to have functioning wasm builds!

**Comment by dromer** [comment]
@chrisuehlinger maybe you can also have a look at https://wasted-audio.github.io/hvcc/docs/03.gen.javascript.html

Likely this is somewhat outdated and missing info now :)

**Comment by dromer** [comment]
Heh, would be nice if we could make https://github.com/Wasted-Audio/hvcc-examples/tree/master/javascript compatible again ;)

**Comment by dromer** [comment]
Hah, the chip example works! I added `Event()` and `RandomizeParameters()`: https://mrtoasted.com/~dreamer/hvcctest/bla3/  (link might change. will push code in a bit)

**Comment by dromer** [comment]
Weirdly I'm unable to get a functioning build at the moment:

**Comment by dromer** [comment]
Hmm, so this definitely has something to do with https://github.com/Wasted-Audio/hvcc/commit/98ecf89646162684c648a448edefa5a22417930b where `hv_{{name}}_new_with_options` is instantiated differently. I've now updated to latest develop and am now stuck on:

**Comment by dromer** [comment]
woot, fixed \o/

**Comment by dromer** [comment]
and we got the first chip example uploaded to gh-pages!
https://wasted-audio.github.io/hvcc-examples-js/

**Comment by dromer** [comment]
@chrisuehlinger I've updated the js docs. do you think this makes sense?

Ideally it needs some more contextual information I suppose. However, people should just have a look at the example output to really see how it works.

**Pull request merged**
