### PR TITLE
Fixed irc.yml to support multi line commit messages. ({'"{ (({}}}})[[(((

### PR DESCRIPTION
**Pull request by giuliomoro**
no amount of garbage can break this thanks to JSON sanitisation

### CODE REVIEW

**Comment by dromer** [comment]
yay!

**Comment by dromer** [comment]
@giuliomoro of course the issue was _not_ multi-line messages, but apostrophe's

**Comment by giuliomoro** [comment]
this works for all of them: multiline (which is what was still failing), and then any apostrophes, quotes, parenthesis etc. Everything properly escaped.

**Comment by dromer** [comment]
multi-line never failed, but great that this catches all these special cases!

**Pull request merged**
